=== nishad/uccass/ADOdb/xmlschema.dtd
<?xml version="1.0"?>
<!-- Modified by Jakub Holy -->
<!DOCTYPE adodb_schema [
<!ELEMENT schema (table*, sql*,sequence*)>
<!ATTLIST schema version CDATA #REQUIRED>
<!ELEMENT table ((field+|DROP), constraint*, descr?, index*, data*, opt*)>
<!ELEMENT field ((NOTNULL|KEY|PRIMARY)?, (AUTO|AUTOINCREMENT)?, (DEFAULT|DEFDATE|DEFTIMESTAMP)?, NOQUOTE, constraint, descr?)>
<!ELEMENT data (row+)>
<!ELEMENT row (f+)>
<!ELEMENT f (#CDATA)>
<!ELEMENT descr (#CDATA)>
<!ELEMENT NOTNULL EMPTY>
<!ELEMENT KEY EMPTY>
<!ELEMENT PRIMARY EMPTY>
<!ELEMENT AUTO EMPTY>
<!ELEMENT AUTOINCREMENT EMPTY>
<!ELEMENT DEFAULT EMPTY>
<!ELEMENT DEFDATE EMPTY>
<!ELEMENT DEFTIMESTAMP EMPTY>
<!ELEMENT NOQUOTE EMPTY>
<!ELEMENT DROP EMPTY> <!-- Drop the table -->
<!ELEMENT constraint (#CDATA)>
<!-- An additional option (e.g. table level) - ex.: type=ISAM. Use only one opt 
for a given platform, separate multiple options by commas - see ADOdb dictionary's CreateTableSQL -->
<!ELEMENT opt (#CDATA)>	
<!ATTLIST table name CDATA #REQUIRED platform CDATA #IMPLIED version CDATA #IMPLIED>
<!ATTLIST field name CDATA #REQUIRED type (C|C2|X|X2|B|D|T|L|I|F|N) #REQUIRED size CDATA #IMPLIED>
<!ATTLIST data platform CDATA #IMPLIED>
<!ATTLIST f name CDATA #IMPLIED>
<!ATTLIST DEFAULT value CDATA #REQUIRED>
<!-- The platform may be either: 'platform1[|platform2...]' or: '- platform1'
	For available platforms see ADOdb dictionary; ex.: postgres, mysql.
	'- mysql' tells us to apply it to all databases but mysql. -->
<!ATTLIST constraint platform CDATA #IMPLIED>
<!ATTLIST opt platform CDATA #IMPLIED>
<!ELEMENT index ((col+|DROP), CLUSTERED?, BITMAP?, UNIQUE?, FULLTEXT?, HASH?, descr?)>
<!ELEMENT col (#CDATA)>
<!ELEMENT CLUSTERED EMPTY>
<!ELEMENT BITMAP EMPTY>
<!ELEMENT UNIQUE EMPTY>
<!ELEMENT FULLTEXT EMPTY>
<!ELEMENT HASH EMPTY>
<!ATTLIST index name CDATA #REQUIRED platform CDATA #IMPLIED>

<!ELEMENT sql (query+, descr?)>
<!ELEMENT query (#CDATA)>
<!ATTLIST sql name CDATA #IMPLIED platform CDATA #IMPLIED, key CDATA, prefixmethod (AUTO|MANUAL|NONE) >

<!-- sequence tells adodb-xmlschema to create a sequence of the given name and with 
the given initial value (if any). If drop="true" the sequence will be dropped. -->
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence name CDATA #REQUIRED initialValue CDATA #IMPLIED 
	platform CDATA #IMPLIED drop CDATA #IMPLIED>
] >

=== nishad/uccass/survey-adodb_schema.xml
<?xml version="1.0"?>
<!DOCTYPE adodb_schema PUBLIC "-//ADODB//DTD adodb_schema//EN" "ADOdb/xmlschema.dtd">
<schema version="0.3">

<!--
Manual changes of schema imported from a MySQL DB build with uccass sql script:
 1. Remove the attribute size of fields of type I (an extension of MySQL, only influences a display of the field). Postgres Adodb datadict doesn't ignore it as it should.
 2. Add <opt platform="mysql">CHARACTER SET latin1 type=MyISAM</opt> or <opt platform="mysql">type=MyISAM</opt> to the tables (see the original sql).
 3. Add <opt platform="postgres">WITHOUT OIDS</opt> to the table 'questions' to prevent conflict with postgres' autogenerated column name.
 4. Change index names to be unique by prepending table names.
 5. Replace tables used to simulate sequences in MySql by elements as: sequence name="users_sequence" initialValue="29". (Initial value is taken from the data inserted into the table)
 
NOTE ON MYSQL 'CHARACTER SET latin1'
 This is essential even if you want uccass to use utf-8 because in main.class.php we set the 
 connection to latin1 as well, which prevents MySQL from undesired conversions between encodings.
 Or you may change latin1 to utf8 (MySQL name for utf-8) at both places.
-->

<!-- -->
<sequence name="answer_types_sequence" drop="true"/>
<sequence name="answer_values_sequence" drop="true"/>
<sequence name="dependencies_sequence" drop="true"/>
<sequence name="questions_sequence" drop="true"/>
<sequence name="results_sequence" drop="true"/>
<sequence name="results_text_sequence" drop="true"/>
<sequence name="surveys_sequence" drop="true"/>
<sequence name="users_sequence" drop="true"/>
<sequence name="report_questions_sequence" drop="true"/>
<sequence name="reports_sequence" drop="true"/>
<sequence name="sequence" drop="true"/>
<!-- -->
  
<table name="answer_types">
    <field name="aid" type="I">
      <KEY/>
      <DEFAULT value="0"/>
    </field>
    <field name="name" type="C" size="50">
      <NOTNULL/>
	  <DEFAULT value=""/>
    </field>
    <field name="type" type="C" size="5">
      <NOTNULL/>
      <DEFAULT value="T"/>
    </field>
    <field name="label" type="C" size="255">
      <NOTNULL/>
	  <DEFAULT value=""/>
    </field>
    <field name="sid" type="I">
      <NOTNULL/>
      <DEFAULT value="0"/>
    </field>
	<opt platform="mysql">CHARACTER SET latin1 type=MyISAM</opt>
    <data>
      <row><f>1</f><f>Textbox (Large)</f><f>T</f><f></f><f>2</f></row>
      <row><f>2</f><f>Sentence (255 characters)</f><f>S</f><f></f><f>2</f></row>
      <row><f>3</f><f>Yes / No</f><f>MS</f><f></f><f>2</f></row>
      <row><f>4</f><f>True / False</f><f>MS</f><f></f><f>2</f></row>
      <row><f>5</f><f>Agree / Disagree (5 options)</f><f>MS</f><f></f><f>2</f></row>
      <row><f>6</f><f>Yes / No / Don't Know - Frequency</f><f>MS</f><f></f><f>2</f></row>
      <row><f>9</f><f>Discrimination Types</f><f>MM</f><f>Check all that apply</f><f>2</f></row>
      <row><f>10</f><f>Apply to Extent</f><f>MS</f><f></f><f>2</f></row>
      <row><f>11</f><f>High / Moderate / Low</f><f>MS</f><f></f><f>2</f></row>
      <row><f>12</f><f>Yes / No - Affected By</f><f>MS</f><f></f><f>2</f></row>
      <row><f>13</f><f>Well / Borderline / Never</f><f>MS</f><f></f><f>2</f></row>
      <row><f>14</f><f>Like / Borderline / Dislike</f><f>MS</f><f></f><f>2</f></row>
      <row><f>15</f><f>Yes / Maybe / Not</f><f>MS</f><f></f><f>2</f></row>
      <row><f>16</f><f>Agree / Disagree / Don't Use Them</f><f>MS</f><f></f><f>2</f></row>
      <row><f>103</f><f>Time in Current Position</f><f>MS</f><f></f><f>2</f></row>
      <row><f>107</f><f>Gender</f><f>MS</f><f></f><f>2</f></row>
      <row><f>108</f><f>Race</f><f>MS</f><f></f><f>2</f></row>
      <row><f>24</f><f>None</f><f>N</f><f></f><f>2</f></row>
      <row><f>312</f><f>Discrimination Types</f><f>MM</f><f>Check all that apply</f><f>0</f></row>
      <row><f>26</f><f>Yes / No / NA</f><f>MS</f><f></f><f>2</f></row>
      <row><f>30</f><f>None to Extremely High with Slight</f><f>MS</f><f></f><f>2</f></row>
      <row><f>311</f><f>Apply to Extent</f><f>MS</f><f></f><f>0</f></row>
      <row><f>39</f><f>Good / Okay / Bad</f><f>MS</f><f></f><f>2</f></row>
      <row><f>310</f><f>High / Moderate / Low</f><f>MS</f><f></f><f>0</f></row>
      <row><f>110</f><f>Agree / Disagree (3 options)</f><f>MS</f><f></f><f>2</f></row>
      <row><f>111</f><f>Great Extent / Moderate / None</f><f>MS</f><f></f><f>2</f></row>
      <row><f>112</f><f>None / Moderate / High</f><f>MS</f><f></f><f>2</f></row>
      <row><f>113</f><f>Low / Moderate / High</f><f>MS</f><f></f><f>2</f></row>
      <row><f>116</f><f>Amount (1 to 10, more than 10)</f><f>MS</f><f></f><f>2</f></row>
      <row><f>117</f><f>Amount (0 - 10, more than 10)</f><f>MS</f><f></f><f>2</f></row>
      <row><f>169</f><f>None (Blank)</f><f>N</f><f></f><f>5</f></row>
      <row><f>168</f><f>Text</f><f>T</f><f></f><f>5</f></row>
      <row><f>167</f><f>Sentence</f><f>S</f><f></f><f>5</f></row>
      <row><f>166</f><f>Race</f><f>MS</f><f></f><f>5</f></row>
      <row><f>165</f><f>Gender</f><f>MS</f><f></f><f>5</f></row>
      <row><f>164</f><f>Yes / No</f><f>MS</f><f></f><f>5</f></row>
      <row><f>163</f><f>Discrimination Options</f><f>MM</f><f></f><f>5</f></row>
      <row><f>162</f><f>Yes / No (bother me)</f><f>MS</f><f></f><f>5</f></row>
      <row><f>161</f><f>High / Moderate / Low</f><f>MS</f><f></f><f>5</f></row>
      <row><f>160</f><f>Prepared / Not Prepared</f><f>MS</f><f></f><f>5</f></row>
      <row><f>159</f><f>Great Extent / Slight Extent / Not at all</f><f>MS</f><f></f><f>5</f></row>
      <row><f>158</f><f>Helpful / Not Helpful</f><f>MS</f><f></f><f>5</f></row>
      <row><f>157</f><f>14+ days / 1-3 days</f><f>MS</f><f></f><f>5</f></row>
      <row><f>156</f><f>None / Slight / High</f><f>MS</f><f></f><f>5</f></row>
      <row><f>155</f><f>No / Yes - Frequently</f><f>MS</f><f></f><f>5</f></row>
      <row><f>154</f><f>Agree / Disagree</f><f>MS</f><f></f><f>5</f></row>
      <row><f>309</f><f>Yes / No - Affected By</f><f>MS</f><f></f><f>0</f></row>
      <row><f>308</f><f>Well / Borderline / Never</f><f>MS</f><f></f><f>0</f></row>
      <row><f>307</f><f>Like / Borderline / Dislike</f><f>MS</f><f></f><f>0</f></row>
      <row><f>306</f><f>Yes / Maybe / Not</f><f>MS</f><f></f><f>0</f></row>
      <row><f>304</f><f>Time in Current Position</f><f>MS</f><f></f><f>0</f></row>
      <row><f>305</f><f>Agree / Disagree / Don't Use Them</f><f>MS</f><f></f><f>0</f></row>
      <row><f>303</f><f>Gender</f><f>MS</f><f></f><f>0</f></row>
      <row><f>302</f><f>Race</f><f>MS</f><f></f><f>0</f></row>
      <row><f>301</f><f>Yes / No / NA</f><f>MS</f><f></f><f>0</f></row>
      <row><f>300</f><f>None to Extremely High with Slight</f><f>MS</f><f></f><f>0</f></row>
      <row><f>299</f><f>Good / Okay / Bad</f><f>MS</f><f></f><f>0</f></row>
      <row><f>298</f><f>Agree / Disagree (3 options)</f><f>MS</f><f></f><f>0</f></row>
      <row><f>297</f><f>Great Extent / Moderate / None</f><f>MS</f><f></f><f>0</f></row>
      <row><f>296</f><f>None / Moderate / High</f><f>MS</f><f></f><f>0</f></row>
      <row><f>295</f><f>Low / Moderate / High</f><f>MS</f><f></f><f>0</f></row>
      <row><f>294</f><f>Amount (1 to 10, more than 10)</f><f>MS</f><f></f><f>0</f></row>
      <row><f>293</f><f>Amount (0 - 10, more than 10)</f><f>MS</f><f></f><f>0</f></row>
      <row><f>292</f><f>Textbox (Large)</f><f>T</f><f></f><f>0</f></row>
      <row><f>291</f><f>Sentence (255 characters)</f><f>S</f><f></f><f>0</f></row>
      <row><f>290</f><f>None</f><f>N</f><f></f><f>0</f></row>
      <row><f>313</f><f>Yes / No / Don't Know - Frequency</f><f>MS</f><f></f><f>0</f></row>
      <row><f>314</f><f>Agree / Disagree (5 options)</f><f>MS</f><f></f><f>0</f></row>
      <row><f>315</f><f>True / False</f><f>MS</f><f></f><f>0</f></row>
      <row><f>316</f><f>Yes / No</f><f>MS</f><f></f><f>0</f></row>
    </data>
  </table>
  
<sequence name="answer_types_sequence" initialValue="876"/>
  
<table name="answer_values">
    <field name="avid" type="I">
      <KEY/>
      <DEFAULT value="0"/>
    </field>
    <field name="aid" type="I">
      <NOTNULL/>
      <DEFAULT value="0"/>
    </field>
    <field name="value" type="C" size="255">
      <NOTNULL/>
	  <DEFAULT value=""/>
    </field>
    <field name="numeric_value" type="I">
      <NOTNULL/>
      <DEFAULT value="0"/>
    </field>
    <field name="image" type="C" size="255">
      <NOTNULL/>
	  <DEFAULT value=""/>
    </field>
    <index name="idx_answer_values_aid">
      <col>aid</col>
    </index>
    <opt platform="mysql">CHARACTER SET latin1 type=MyISAM</opt>
	<data>
      <row><f>1</f><f>3</f><f>Yes</f><f>1</f><f>bar.gif</f></row>
      <row><f>2</f><f>3</f><f>No</f><f>2</f><f>bar.gif</f></row>
      <row><f>3</f><f>4</f><f>True</f><f>1</f><f>bar.gif</f></row>
      <row><f>4</f><f>4</f><f>False</f><f>2</f><f>bar.gif</f></row>
      <row><f>5</f><f>5</f><f>Strongly Agree</f><f>1</f><f>bar.gif</f></row>
      <row><f>6</f><f>5</f><f>Agree</f><f>2</f><f>bar.gif</f></row>
      <row><f>7</f><f>5</f><f>Neither agree nor disagree</f><f>3</f><f>bar.gif</f></row>
      <row><f>8</f><f>5</f><f>Disagree</f><f>4</f><f>bar.gif</f></row>
      <row><f>9</f><f>5</f><f>Strongly Disagree</f><f>5</f><f>bar.gif</f></row>
      <row><f>10</f><f>6</f><f>No</f><f>1</f><f>bar.gif</f></row>
      <row><f>11</f><f>6</f><f>Yes - Once in a while</f><f>2</f><f>bar.gif</f></row>
      <row><f>12</f><f>6</f><f>Yes - Frequently</f><f>3</f><f>bar.gif</f></row>
      <row><f>13</f><f>6</f><f>Yes - Very frequently</f><f>4</f><f>bar.gif</f></row>
      <row><f>14</f><f>6</f><f>Don't know</f><f>5</f><f>bar.gif</f></row>
      <row><f>25</f><f>9</f><f>No</f><f>1</f><f>bar.gif</f></row>
      <row><f>26</f><f>9</f><f>Yes - National Orgin</f><f>2</f><f>bar.gif</f></row>
      <row><f>27</f><f>9</f><f>Yes - Religious</f><f>3</f><f>bar.gif</f></row>
      <row><f>28</f><f>9</f><f>Yes - Gender</f><f>4</f><f>bar.gif</f></row>
